/**
 * Vault configuration for credential-isolating proxy mode.
 *
 * When configured, model API requests are routed through a vault sidecar
 * (nginx reverse proxy) that injects credentials. The OpenClaw process
 * never sees the actual API keys.
 *
 * Each entry in `proxies` maps a provider name to the vault proxy URL for
 * that provider. The proxy URL replaces the provider's `baseUrl`, and auth
 * resolution returns a dummy API key (the vault injects the real one).
 */
export type VaultConfig = {
  /** Enable vault proxy mode. When false or omitted, vault config is ignored. */
  enabled?: boolean;

  /**
   * Provider-to-proxy URL mappings.
   *
   * Keys are provider names (matching `models.providers` keys).
   * Values are the vault proxy base URLs (e.g. "http://vault:8081").
   *
   * Example:
   * ```json
   * {
   *   "openai": "http://vault:8081",
   *   "anthropic": "http://vault:8082",
   *   "deepgram": "http://vault:8083"
   * }
   * ```
   */
  proxies?: Record<string, string>;

  /** Path to vault.age encrypted secrets file. Defaults to vault.age alongside openclaw.json. */
  file?: string;

  /**
   * Age public key (recipient, `age1...`). Safe to store in config — used only for encryption.
   * Generated by `openclaw vault init` and stored here for subsequent `vault add` operations.
   */
  publicKey?: string;
};
